### ISSUE TITLE
Orange and Green walls?

### ISSUE THREAD

**Issue by randoomdude** [veeenu/eldenring-practice-tool#100]
Just wondering what the option to enable wall boxes actually is, why are there a orange and green ones? Also not sure what the blue, red and yellow means for the character hitboxes, they seem to turn red when attacking though, is it just a sign for a upcoming attack?
![Elden Ring 2024 07 09 - 20 56 31 02 DVR mp4_snapshot_01 37 103](https://github.com/veeenu/eldenring-practice-tool/assets/6027132/31251fbb-f7b0-4617-997c-e84c51f6f19d)

**Comment by veeenu** [comment]
I'm not 100% sure about weapon hotboxes. The wall meshes are a high poly one that the game uses for particles/spells collisions and a low poly one that the game uses for characters collisions.
