### ISSUE TITLE
No DLC ashes of war and spawned cookbooks are broken

### ISSUE THREAD

**Issue by elp521** [veeenu/eldenring-practice-tool#109]
I have looked the entire list of items through multiple times and couldn't find any of the new ashes of war. also, i tried to give myself some of the cook books and it didn't add anything to my crafting menu. it seems to be an issue with all the cookbooks, not just from the DLC. Not sure if there is an easy fix to this on my end.

**Comment by veeenu** [comment]
I'll look into AoWs but cookbooks not working is a known issue, as the mechanics are different from just spawning the item.
