### ISSUE TITLE
The command menu does not load, and the shortcut does not take effect

### ISSUE THREAD

**Issue by siwoya** [veeenu/eldenring-practice-tool#110]
I'm using the 1.12ER, 1.7.1 tool.
I don't get le menu appearing at the upper left of the screen but the icon of the Spectral Steed Whistle is being changed.

EAC is being bypassed using the steam_appid.txt
I added Practice Tool as an exception to Windows Defender
I tried previous versions of Practice Tool and ER,But it didn't work out
I can't press the button to activate any of the function

Here's my log.
[jdsd_er_practice_tool.log](https://github.com/user-attachments/files/16322911/jdsd_er_practice_tool.log)
Thank you.

**Comment by veeenu** [comment]
That tends to happen when you have other overlay software running, like RivaTuner or similar. In general it should behave pretty well against Steam's overlay but RTSS is known to be problematic. Is that the case?

**Comment by siwoya** [comment]
I know why.When I exit Fraps, the menu loads successfully.Thank you for taking the time to reply.

**Comment by veeenu** [comment]
Oh, yeah, unfortunately it is known that other overlay software that uses the same detouring techniques as the tool is at high risk of conflict. Good to know you solved it!
