### ISSUE TITLE
Practice Tool does not launch

### ISSUE THREAD

**Issue by MrSolon** [veeenu/eldenring-practice-tool#117]
Hi everyone,

I have issue to launch PT.
I followed every step to the letter : EAC disabled with the text method, antivirus disabled, ER launched via .exe and not via steam, steam on. My GPU driver is up to date. I rebooted my PC. And still, PT doesn't launch. When I click on the jdsd_er_practice_tool.exe (with ER launched off course), nothing happens.

Any idea please?
Thank you :)
Solon

**Comment by veeenu** [comment]
Could you please try [doing this](https://github.com/veeenu/eldenring-practice-tool/blob/main/TROUBLESHOOTING.md#i-found-an-issue-what-do-i-do) and uploading a log?
