### ISSUE TITLE
Bug related to Whetblades and Crafting Kit

### ISSUE THREAD

**Issue by ShinsoKaii** [veeenu/eldenring-practice-tool#134]
Hi! I downloaded the practice tool to play the dlc and get there faster, since my only character was at NG+7 and i didn't want to do the dlc at this level. However, after giving myself the Whetblades and crafting kit, i can't craft items nor select affinities for ashes of war, not even at the Roundtable or Iji. I tried getting rid of the item but it dosn't give me an option to discart it
![imagem_2024-09-25_063135521](https://github.com/user-attachments/assets/db5d8623-bdae-4b81-adcf-bb47cb7f366b)
![imagem_2024-09-25_063150330](https://github.com/user-attachments/assets/54df1dca-1634-4ac4-b555-7ca78cf9a869)

**Comment by veeenu** [comment]
This is a known issue. Whetblades and cookbooks are particular items that are (probably? not sure) tied to an event so you'll have to pick them up manually, unfortunately. There should be no need to discard them.
