### ISSUE TITLE
Speed Enhancer not working

### ISSUE THREAD

**Issue by Tolnin** [veeenu/eldenring-practice-tool#138]
I set it to 10x but my speed doesn't change at all

**Comment by veeenu** [comment]
what version of the tool and what version of the game are you on?

**Comment by Tolnin** [comment]
> what version of the tool and what version of the game are you on?

I was using the latest version of both.  Seems the issue is that I was using Seamless Coop and that somehow broke it, wish it worked with Seamless

**Comment by veeenu** [comment]
Then that is probably the cause. Interaction with other mods is not supported unfortunately, as it requires a multiple of the already nontrivial maintenance effort.
