### ISSUE TITLE
Make flag names more intuitive

### ISSUE THREAD

**Issue by alexisfaintreny** [veeenu/eldenring-practice-tool#19]
Certain skips could be helpful to practice with a collision viewer feature. Don't know how feasible something like that would be but figured I'd give a suggestion!

**Comment by veeenu** [comment]
Not sure if that is exactly what you mean, but there is a collision viewer feature. Might be a bit of a misnomer, but the "hitbox high" and "hitbox low" flags do show that; they show two separate sets of collision meshes.

**Comment by alexisfaintreny** [comment]
Ohhh I'll have to try that out! Sorry about that

**Comment by veeenu** [comment]
No problem! I'm considering changing the flag names so they are more intuitive, so I'm changing this issue's title accordingly.

**Comment by veeenu** [comment]
Improved as of 1.0.3.
