### ISSUE TITLE
Fullscreen freeze

### ISSUE THREAD

**Issue by veeenu** [veeenu/eldenring-practice-tool#23]
The tool makes the game freeze when it is launched fullscreen.

**Comment by nex3** [comment]
For anyone else who's curious, it seems to freeze even if you start the practice tool with the game in a window and then fullscreen the game afterwards.

**Comment by veeenu** [comment]
This was related to #17 -- in 1.0.0 there was no support for changing resolution. The upcoming patch release adds a hook to `ResizeBuffers` that allows correctly releasing and recreating the DX12 objects in the event of a resolution change. As an added bonus, the font has been changed and now the UI scales responsively with the game resolution. 😁
