### ISSUE TITLE
Improve errors on misconfiguration 

### ISSUE THREAD

**Issue by Pennek** [veeenu/eldenring-practice-tool#24]
Removing hotkeys from `jdsd_er_practice_tool.toml` crashes the practice tool and Elden Ring.

Here are my logs:
[jdsd_er_practice_tool.log](https://github.com/veeenu/eldenring-practice-tool/files/8714428/jdsd_er_practice_tool.log)

**Comment by veeenu** [comment]
The correct behavior in case of configuration errors like these would be showing an error window instead of crashing.

**Comment by veeenu** [comment]
Added in 1.0.3.
