### ISSUE TITLE
Instant game crash

### ISSUE THREAD

**Issue by pablomz97** [veeenu/eldenring-practice-tool#27]
Game instantly crashes whenever the practice tool is opened, even on main menu.

Current game/system settings:
Downpatched game to 1.02, EAC enabled via steamapp key, borderless windowed. Nvidia GeForce GTX1050 (mobile)

[Crash log](https://github.com/veeenu/eldenring-practice-tool/files/9091364/log.zip)

**Comment by veeenu** [comment]
It looks like the same issue other people in #21 have. Try clean-installing the GPU drivers, both latest and older ones.

If this solves your issue, please let me know, and also whether it was an older or newer GPU driver that solved it.

**Comment by pablomz97** [comment]
I will keep answering in that thread so you don't have as many dupes and have everthing in the same issue

**Comment by veeenu** [comment]
Closing this issue as we've at least solved it for you!
