### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by ionno** [veeenu/eldenring-practice-tool#29]
Null command queue, is the error when i open the text file and is the main problem and when i open the .exe my game crashes, my game's version is 1.3.2

**Comment by veeenu** [comment]
Please try running the [nightly version](https://github.com/veeenu/eldenring-practice-tool/releases/tag/nightly) and let me know whether the error persists, and post a log here in case. Nightly should contain a fix which, if other people can confirm works, will be upstreamed in the next stable release.

Closing as duplicate of #21. Let us continue there.

**Comment by ionno** [comment]
> Please try running the [nightly version](https://github.com/veeenu/eldenring-practice-tool/releases/tag/nightly) and let me know whether the error persists, and post a log here in case. Nightly should contain a fix which, if other people can confirm works, will be upstreamed in the next stable release.
> 
> Closing as duplicate of #21. Let us continue there.

thanks man, it worked.
