### ISSUE TITLE
"Could not find process"

### ISSUE THREAD

**Issue by julesGlbro** [veeenu/eldenring-practice-tool#30]
The EAC is bypass but when I lauchn the .exe the message "Could not find process" come on 
It's the first time  I try something like this, I don't now how to fix it
![Capture](https://user-images.githubusercontent.com/72040856/183248807-69601ae0-2a6c-49fe-91af-ebec76aa61f0.PNG)

![Capture](https://user-images.githubusercontent.com/72040856/183248860-6c6fff28-5c82-459b-b98f-4cf2422f7541.PNG)

**Comment by veeenu** [comment]
Have you made sure you followed all the [recommended steps](https://github.com/veeenu/eldenring-practice-tool/#my-game-crashes--the-tool-doesnt-start)? Basically every time this has happened to someone, it turned out they had an antivirus running, so my best guess here is this is also the case.

**Comment by julesGlbro** [comment]
I don't followed the second point because the steam_appid.txt method doesn't work so I use an other method.
With only steam_appid.txt EAC still run, but with the fake start_protected_game he doesn't.
For the steam_appid.txt method i only put a .txt where it write 1245620 so I don't understand why EAC run anyway. 
(Sorry for the english mistakes)

**Comment by julesGlbro** [comment]
It's good i find a method 
You have just to erase the .txt at the end of steam_appid
![Capture](https://user-images.githubusercontent.com/72040856/183262431-b5b561c2-efa9-4aa9-87f2-040ec45867cb.PNG)

**Comment by julesGlbro** [comment]
Thanks for your help and the mod
Have a good day
