### ISSUE TITLE
Issue launching

### ISSUE THREAD

**Issue by Hasal222** [veeenu/eldenring-practice-tool#34]
When i launch the tool.exe in the main menu, nothing happens. I dont get error messages, and i dont see the tool ingame. 
[jdsd_er_practice_tool.zip](https://github.com/veeenu/eldenring-practice-tool/files/10366314/jdsd_er_practice_tool.zip)

The log says [ERROR] Thread 'unnamed'  panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: 0x887A0001

**Comment by veeenu** [comment]
I want to understand whether a regression was introduced in the newest release; could you please download the previous release and confirm whether the issue is still happening or not?

**Comment by Hasal222** [comment]
V1.06 has no issue, everything seems to be working.

**Comment by veeenu** [comment]
That's good to know, think I have found the regression. Thank you. Will publish a bugfix release sometime soon

**Comment by veeenu** [comment]
Merging with #35
