### ISSUE TITLE
version 1.0.7 quits upon starting, 1.0.6 works fine

### ISSUE THREAD

**Issue by matwatson** [veeenu/eldenring-practice-tool#35]
Thanks for authoring this super helpful tool. I read 1.0.7 was available and thought I would give it a try. It stops immediately after starting with both Elden Ring 1.07 and 1.08.1. I've attached two log files. Please note that practice tool 1.0.6 works fine with both Elden Ring versions.

[er1.08.1jdsd_er_practice_tool.log](https://github.com/veeenu/eldenring-practice-tool/files/10398545/er1.08.1jdsd_er_practice_tool.log)
[er1.07jdsd_er_practice_tool.log](https://github.com/veeenu/eldenring-practice-tool/files/10398546/er1.07jdsd_er_practice_tool.log)

**Comment by marantz** [comment]
Same Issue occurred to me.

**Comment by veeenu** [comment]
It is most likely the same issue as #34.

@Hasal222 @matwatson @marantz I published a [new nightly](https://github.com/veeenu/eldenring-practice-tool/releases/download/nightly/jdsd_er_practice_tool.zip) with a potential fix. Could you please confirm if the error is gone? If that's the case, I will draft a new release. Thank you!

**Comment by matwatson** [comment]
Thank you, @veeenu. The new nightly works fine with 1.07 and 1.08.1.

**Comment by veeenu** [comment]
Great, thank you for taking the time to test that! I'll publish a new release with this fix soonish, then.

**Comment by veeenu** [comment]
Closed by the [latest release](https://github.com/veeenu/eldenring-practice-tool/releases/tag/1.0.8).
