### ISSUE TITLE
some troubles( 

### ISSUE THREAD

**Issue by Kaba4ok322** [veeenu/eldenring-practice-tool#36]
![image](https://user-images.githubusercontent.com/123824879/215276521-b8ede43e-3f97-4b42-bc35-b35cb0719705.png)
i`m downoload a latest update of  practice tool and had some trubles with it( maybe i doing something wrong ? can u help me pls ?)
i have steam version Elden Ring with downpatching to 1.05 ) launch tool while i`m in the game , and without running a game the same error)

**Comment by veeenu** [comment]
Please check the FAQ on the GitHub readme. You most likely have antivirus software running.

**Comment by veeenu** [comment]
Closing for lack of further feedback
