### ISSUE TITLE
Practice Tool not hooking on Elden Ring 1.0.7 [Null Command Queue]

### ISSUE THREAD

**Issue by DLamiche** [veeenu/eldenring-practice-tool#41]
So, I recently downpatched Elden Ring 1.0.7 and got the latest version of the Practice Tool, but it doesn't hook to the Elden Ring process, or at least, not entirely.
I don't get le menu appearing at the upper left of the screen but the icon of the Spectral Steed Whistle is being changed.

A few notes:
- EAC is being bypassed using the steam_appid.txt
- I wait until the main menu appear to start Practice Tool
- LiveSplit is hooking fine (the nologo mod integrated with it is being applied properly)
- Even though I didn't get any warning from Windows Defender, I added Practice Tool as an exception to it just to be sure
- I tried previous versions of Practice Tool (1.0.8 and 1.0.5) without getting more successful
- I'd like to add that I managed to get Practice Tool to work back in September on ER 1.0.5, so I don't really know what could have happened in between

I'm on Windows 10 version 21H2 (build 19044.2486).
You'll find the logs attached to the issue, I enabled the DXGI debug for it.

Thanks in advance for your time and thanks for creating this tool!
[[LOGS]jdsd_er_practice_tool.zip](https://github.com/veeenu/eldenring-practice-tool/files/11030650/LOGS.jdsd_er_practice_tool.zip)

**Comment by veeenu** [comment]
Hi! Thank you for reporting the issue and taking the time to add all the details! 😁 

It looks like the tool is functioning and processing stuff in the background, just not being rendered. Can you confirm that by trying to press a button to activate a function? (e.g. 5 for no gravity).

If that works, it could be that it is interfering with other overlay renderers -- such as Steam's (but would be weird) or RivaTuner. If you have those running, could you try disabling them?

If it doesn't work, that means that the render loop exits at some point, but that's probably not the case as I see the command queue being invoked over and over.

**Comment by DLamiche** [comment]
You were right! It was RivaTuner, thank you so much!

I've noticed a few things though:
- No function would work when RivaTuner was active (so it wasn't just a rendering issue I guess)
- Even though I hadn't added Elden Ring in RivaTuner, it was still interfering with it
- RivaTuner is tenacious, it kept opening itself again after closing it so I had to rename its executable to prevent that

Anyway, thank you again for your time!

**Comment by veeenu** [comment]
That's great to know! It's too bad I have no idea what Steam does, because the Steam overlay seems to play just fine with it. But now I can take a shot at trying to deal with it! 

> You were right! It was RivaTuner, thank you so much!
> 
> I've noticed a few things though:
> 
>   * No function would work when RivaTuner was active (so it wasn't just a rendering issue I guess)

Mmm, then chances are RivaTuner just overwrites the prac tool's hooks as soon as it enters into the game.

>   * Even though I hadn't added Elden Ring in RivaTuner, it was still interfering with it
> 
>   * RivaTuner is tenacious, it kept opening itself again after closing it so I had to rename its executable to prevent that

Yeah, wonder what it does to be so aggressive.

> Anyway, thank you again for your time!

Thank you for the report and the kind words! Hope you enjoy the tool! 🥂

**Comment by DLamiche** [comment]
So, rather then renaming its executable and closing it, I've found a better way to deal with this.
In RivaTuner (that I want to keep opened), I can either put the "Application detection level" of "global" at "none" so that it's the default for everything, or add the Elden Ring executable and put "Application detection level" at "none" so that it is the exception.
![image](https://user-images.githubusercontent.com/65600546/226689426-d851ee16-b4e7-4ede-9165-0ff91802acfc.png)
