### ISSUE TITLE
Compatibility with new Elden Ring patch 1.09

### ISSUE THREAD

**Issue by agm-dev** [veeenu/eldenring-practice-tool#42]
First of all, I love this software ❤️

Could we please have an updated release to work with Elden Ring patch 1.09? 🙏🙏🙏

**Comment by rumd3x** [comment]
@veeenu if possible, can u also make a guide on how to find the addresses and how to contribute? i'd love to help

**Comment by veeenu** [comment]
Sure! That is also going to take a while as I'm not a super fast writer and there's a lot to be said 😅 but seeing as there is interest in contributions, it would be good to invest in that.

**Comment by veeenu** [comment]
Fixed in [1.1.0](https://github.com/veeenu/eldenring-practice-tool/releases/tag/1.1.0)!
