### ISSUE TITLE
Game freezes and crashes on run of the  tool

### ISSUE THREAD

**Issue by shawncasaus** [veeenu/eldenring-practice-tool#44]
[jdsd_er_practice_tool.zip](https://github.com/veeenu/eldenring-practice-tool/files/11182799/jdsd_er_practice_tool.zip)

Log above. The tool was actually working fine before, but after an update from the game it now refuses to run the tool without crashing.

I have EAC bypassed properly, and anti-cheat turned off, but for some reason it is still failing.

**Comment by veeenu** [comment]
Hey, thank you for reporting this!

It is the first time I see this particular error -- looks like the tool is starting and hooking at least. Then there is a permission error happening on the DX12 pipeline, though I'm not sure what originates that. Debugging these things is a pain.

- Are you by chance running the game in borderless windowed mode? 
- Do you have other overlays running (e.g. RTSS)?
- What about antiviruses/firewalls?
- What is your OS/CPU/GPU?
- Could you please send another log using the [debug layer](https://github.com/veeenu/eldenring-practice-tool#i-found-an-issue-what-do-i-do)?

Thank you!

**Comment by shawncasaus** [comment]
hi! thank you for the reply! I actually was able to fix this issue, I ran both the .exe for the game and the tool as admin and it seemed to do the trick. Not sure why this suddenly became an issue. But yes I was using borderless window mode, as well as having my anti-virus disabled, and my CPU is an AMD 5600x and my GPU is a 6700xt.

**Comment by veeenu** [comment]
One more data point highlighting the fact that borderless is problematic (#37). Will have to look into it. Thank you!

P.S. what happens if you use regular windowed or fullscreen mode? Does it still require admin?

**Comment by shawncasaus** [comment]
yes all options require admin for some reason, not sure why.

**Comment by veeenu** [comment]
Should be closed by #61, feel free to reopen if not the case once the new release drops
