### ISSUE TITLE
Menu not opening

### ISSUE THREAD

**Issue by JoMamasLlama** [veeenu/eldenring-practice-tool#45]
None of the keybindings are working most importantly the one to open the menu "0" I've also tried changing it to "\" but still didn't work. I've done everything downloading it and running the game from the .exe adding the steam_appid.txt file. Also tried injecting the dll into the game but nothing worked.

**Comment by veeenu** [comment]
If you are trying to run the tool on current patch, it's supposed to not work as I haven't got around to updating it yet.

Otherwise, please follow the [troubleshooting steps](https://github.com/veeenu/eldenring-practice-tool/#troubleshooting--faq) and post a log so we can find out what's wrong.

**Comment by JoMamasLlama** [comment]
Ah, I see I was running it on the current patch thanks for clarifying!
