### ISSUE TITLE
the tool won't open

### ISSUE THREAD

**Issue by Hoaqin1** [veeenu/eldenring-practice-tool#48]
What happens when I double click the .exe file is that it will open but the screen will not appear and a message appearing later that some files were extracted from the zip and that they were modified or new files were created and asks me if I want to put it in the archive.

**Comment by veeenu** [comment]
As stated in the first few lines of the [README](https://github.com/veeenu/eldenring-practice-tool), you should extract the archive before using the tool.

**Comment by Hoaqin1** [comment]
can i just extract it anywhere or somewhere specific?

**Comment by veeenu** [comment]
Wherever you like

**Comment by Hoaqin1** [comment]
worked thank you
