### ISSUE TITLE
1.10.1 Patch broke the tool

### ISSUE THREAD

**Issue by Stefanistkuhl** [veeenu/eldenring-practice-tool#74]
when i lauch the tool the doenst show any error but just wont show up anymore since the patch
[jdsd_er_practice_tool.log](https://github.com/veeenu/eldenring-practice-tool/files/13906720/jdsd_er_practice_tool.log)
edit: i use the seemless coop mod if that is importat to know

**Comment by veeenu** [comment]
Can you please test the [nightly release](https://github.com/veeenu/eldenring-practice-tool/releases/tag/nightly) and report whether it works on the new patch?

It would be helpful to speed things up. I have not been able to validate that myself properly yet -- ran the update automatically during a few minutes' break.

**Comment by Stefanistkuhl** [comment]
jup works however i didnt to any logging and only teste all no damage and no death
