### ISSUE TITLE
Game crashes once back in focus after loading Practice Tool

### ISSUE THREAD

**Issue by afxwinter** [veeenu/eldenring-practice-tool#84]
[jdsd_er_practice_tool.log](https://github.com/veeenu/eldenring-practice-tool/files/14934961/jdsd_er_practice_tool.log)
I have followed all troubleshooting steps and this is still happening.
I've also tried the previous and the nightly builds.  
I have re-installed Elden Ring as well.

**Comment by afxwinter** [comment]
My apologies!  I missed the step to edit the .toml

Windows 10 64
4090 RTX GPU
Latest Nvidia drivers
i9 gen 10 Intel CPU
Elden Ring has raytracing off and set to borderless window

[jdsd_er_practice_tool.log](https://github.com/veeenu/eldenring-practice-tool/files/14936854/jdsd_er_practice_tool.log)

**Comment by veeenu** [comment]
Can you please check if you can reproduce with fullscreen and windowed mode? The tool isn't getting injected because, by the time it requests a Direct3D12 device, an error we don't have any control over happens. Borderless could be a culprit but I'm not excluding the cause could be some other third party application. Do you have any, e.g. RTSS/visual mods?

**Comment by afxwinter** [comment]
I just did a full driver DDU and reinstall.
I've attached fullscreen and windowed logs.
These are without RTSS enabled.  However I have had previous versions of this tool work with previous ER patches with RTSS on in fullscreen on this same hardware config.
[fullscreen.log](https://github.com/veeenu/eldenring-practice-tool/files/14948202/fullscreen.log)
[windowed.log](https://github.com/veeenu/eldenring-practice-tool/files/14948203/windowed.log)

**Comment by veeenu** [comment]
These give out the same errors. Do you have other mods installed, by chance?

**Comment by afxwinter** [comment]
I get the same logs and behavior with or without other mods installed.
I just tried going back to ER version 1.02 and couldn't get the tool to load there either.  Will try version 1.05 next.  I'm wondering if this is an issue with the latest Nvidia driver.  Will try earlier versions of these next.

**Comment by afxwinter** [comment]
[1.03_log.zip](https://github.com/veeenu/eldenring-practice-tool/files/14961080/1.03_log.zip)
Here is the log from game version 1.05 and the practice tool version 1.03.
I could tell that it was working when alt-tabbed but as soon as I gained focus of the game it immediately crashed again.

**Comment by afxwinter** [comment]
Figured it out!  It was indeed Riva Statistics Server.  When I tested it previously it had automatically restarted without my knowledge.  Forcing it to not interact with any applications solved my issue!  Thank you for your help and the amazing tool!

**Comment by afxwinter** [comment]
Figured it out!  It was indeed Riva Statistics Server.  When I tested it previously it had automatically restarted without my knowledge.  Forcing it to not interact with any applications solved my issue!  Thank you for your help and the amazing tool!
