### ISSUE TITLE
TOOL WON'T LOAD

### ISSUE THREAD

**Issue by Monty1922** [veeenu/eldenring-practice-tool#85]
I keep getting this error whenever I try to load the tool, I did all the steps correctly and it's still happening
![Screenshot_55](https://github.com/veeenu/eldenring-practice-tool/assets/166679935/c9211f6e-9349-49d8-9ae8-85fc0bde8359)

**Comment by veeenu** [comment]
I don't think you have.

That error happens when the DLL and the exe are not in the same directory. Have you extracted the zip file to a directory (_any_ directory will do) and double clicked the exe? That's all there is to do.

**Comment by Monty1922** [comment]
This is the game directory 
![Screenshot_56](https://github.com/veeenu/eldenring-practice-tool/assets/166679935/268a221d-df89-4e57-8cc0-545ccb59b3ec)

**Comment by veeenu** [comment]
There's all manners of external stuff in there. The practice tool won't ever offer any compatibility in such a case. The tool is only meant to work against vanilla, unmodded Elden Ring.

Good news though, you can move your current installation elsewhere and download another fresh copy of the game if you want to use the tool.

At any rate, I ask again, *are you sure* you extracted the zip file? I don't see the `jdsd_er_practice_tool.dll` nor `jdsd_er_practice_tool.exe` in there, only the `jdsd_er_practice_tool.toml` file. Which is not sufficient, you need all three files to be in the same directory, as implied by "extract the zip file to a directory".

**Comment by Monty1922** [comment]
After checking I added all the files to the game directory and the tool actually loaded ( without renaming  'jdsd_er_practice_tool.dll' )  but the game keeps crashing. when I changed 'jdsd_er_practice_tool.dll' to 'dinput8.dll' it gave me the same error above. And yes I did extract it to a directory

**Comment by veeenu** [comment]
That's progress though. You don't need to rename the file to `dinput8.dll` _unless_ you want to use the right shift loading method. Maybe the documentation is not super clear on that?

The problem now is that you have too much external stuff and mods and I'm pretty confident one of them is messing with things in some way. That's not going to be supported, as I can't know in which ways the game may have been modified by tools I have no control over. Try getting a completely vanilla installation of the game going and see if it works with that.
