### ISSUE TITLE
"The specified file could not be found"

### ISSUE THREAD

**Issue by Halarju** [veeenu/eldenring-practice-tool#87]
when i open eldenring.exe then practice tool cmd shows up and it shows "The specified file could not be found" what can i do?

**Comment by veeenu** [comment]
- Have you extracted the zip file to a directory?
- If you are using the exe, you need to _not_ rename the DLL file to `dinput8.dll`. Re-extract the file and just run the executable.

**Comment by Halarju** [comment]
i deleted dinput8.dll and same thing happened

**Comment by Halarju** [comment]
ok so i managed to fix this problem but when i open the game and then i open practice tool the game stops for a few seconds and then crashes

**Comment by veeenu** [comment]
Can you try with the newest release?

**Comment by Halarju** [comment]
thanks so much
