### ISSUE TITLE
DLC Items

### ISSUE THREAD

**Issue by TheMrGeeBee** [veeenu/eldenring-practice-tool#89]
Does it include DLC items? Tried to spawn items in the Dark Realm, but there is nothing there in the tool.

**Comment by veeenu** [comment]
It does not, at the moment. The current release is just for binary compatibility for the new patch but it has no new features.

The item IDs have to be manually curated as no publicly available, well organized list of items with their IDs exists online.

I am currently playing through the DLC myself and would like to avoid spoilers, so this addition is going to take a while and there is no ETA. I accept contributions but I won't review them either until I'm done, for the same reasons.

I also don't want to rush my playthrough as it's not like From releases a DLC every other day. Please be patient.
