### ISSUE TITLE
no me permite ejecutar el practice tool

### ISSUE THREAD

**Issue by chekeoale** [veeenu/eldenring-practice-tool#90]
me da el error, donde me dice que el programa no se puede ejecutar debido a que no se encuentra la carpeta del juego... realice el proceso que me recomendaron en la pagina pero tampoco me funciono, que puedo hacer?

**Comment by veeenu** [comment]
I don't speak spanish, I'm sorry, so let's continue this in english please.
I am not sure what error specifically you are talking about, I have never run into a "game file not found" error before. Please post screenshots of the issue you have run into.

But before doing that, please make doubly sure you **followed all instructions exactly**. If you want to run it from the exe, _do not_ rename the .dll file. Make sure you have extracted all the files to a folder. Make sure you are not running Windows Defender or other antiviruses as they will block. Reread everything on the [readme](https://github.com/veeenu/eldenring-practice-tool?tab=readme-ov-file) and on the [troubleshooting guide](https://github.com/veeenu/eldenring-practice-tool/blob/main/TROUBLESHOOTING.md).

**Comment by veeenu** [comment]
Closing for lack of feedback, feel free to reopen
