### ISSUE TITLE
Could not check for new version: Error 403

### ISSUE THREAD

**Issue by zezian** [veeenu/eldenring-practice-tool#91]
![Sem título0000](https://github.com/veeenu/eldenring-practice-tool/assets/35636351/66aa5729-1439-4bdd-a136-0c127d43caa1)

Was working fine, and now it isn't, not sure what the issue is, sorry for bothering u with this.

**Comment by veeenu** [comment]
No bother at all! Looks like a temporary problem, or some network issue on your end. The endpoint is working for me. Try again later, or check if you have antiviruses/windows defender blocking the tool.

**Comment by zezian** [comment]
it's working again! ty
